# This file was generated by GoReleaser. DO NOT EDIT.
cask "squadron" do
  name "squadron"
  desc "CLI for defining and running AI agents and multi-agent missions"
  homepage "https://github.com/mlund01/squadron"
  version "0.0.14"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "squadron"

  on_macos do
    on_intel do
      url "https://github.com/mlund01/squadron/releases/download/v#{version}/squadron_darwin_amd64.tar.gz"
      sha256 "bc3c68b29954c2868a18592dce0874f1c4234ce27ce4cbcf0a51991212b01754"
    end
    on_arm do
      url "https://github.com/mlund01/squadron/releases/download/v#{version}/squadron_darwin_arm64.tar.gz"
      sha256 "4f6608f6df6ff2b22504756104eeb5e8c461dcc8839f5b1f4c399725a1c7a8d3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mlund01/squadron/releases/download/v#{version}/squadron_linux_amd64.tar.gz"
      sha256 "dc7c437916ebd0fbdd607d149a0bb475e2df5c4324e7b092bcd36c8bcabc7ff0"
    end
    on_arm do
      url "https://github.com/mlund01/squadron/releases/download/v#{version}/squadron_linux_arm64.tar.gz"
      sha256 "71e33b383702e47007620408604991fe9e2e49f913e3257308ba45ff749d8c50"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/squadron"]
    end
  end

  # No zap stanza required
end
