# This file was generated by GoReleaser. DO NOT EDIT.
cask "squadron" do
  name "squadron"
  desc "CLI for defining and running AI agents and multi-agent workflows"
  homepage "https://github.com/mlund01/squadron"
  version "0.0.9"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "squadron"

  on_macos do
    on_intel do
      url "https://github.com/mlund01/squadron/releases/download/v#{version}/squadron_darwin_amd64.tar.gz"
      sha256 "382d2d00d7b891ebf1690cf75631c28edb7600c86b4c682b3871073eab78f710"
    end
    on_arm do
      url "https://github.com/mlund01/squadron/releases/download/v#{version}/squadron_darwin_arm64.tar.gz"
      sha256 "aeca9d86d24d9164fe91e6cc9b67a3e52ca5f84022f2f526689a2f56947429aa"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mlund01/squadron/releases/download/v#{version}/squadron_linux_amd64.tar.gz"
      sha256 "a4dc0ca51b888956eae8fcd91f86f38959c68a52c74fb534b0ec12292aa6b061"
    end
    on_arm do
      url "https://github.com/mlund01/squadron/releases/download/v#{version}/squadron_linux_arm64.tar.gz"
      sha256 "fbbfde535531c6a5bf4fd1473be8c1421c9f1920a37897b65e744ce4c0fd802f"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/squadron"]
    end
  end

  # No zap stanza required
end
