# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Squadron < Formula
  desc "CLI for defining and running AI agents and multi-agent workflows"
  homepage "https://github.com/mlund01/squadron"
  version "0.0.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mlund01/squadron/releases/download/v0.0.6/squadron_darwin_amd64.tar.gz"
      sha256 "d67f6b1f8f6aa250d3c68fbaaf0756aebde55d1215ff2fe1f82694750ca9802e"

      def install
        bin.install "squadron"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mlund01/squadron/releases/download/v0.0.6/squadron_darwin_arm64.tar.gz"
      sha256 "b96c79f73036932225f07a4103fa6ea28a126eddcb592761082464f8c16ec660"

      def install
        bin.install "squadron"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mlund01/squadron/releases/download/v0.0.6/squadron_linux_amd64.tar.gz"
      sha256 "b01720a24f90a8b275b9c682a2b39dbc37cf892dc6c2773388a84e7a192cf5b7"
      def install
        bin.install "squadron"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mlund01/squadron/releases/download/v0.0.6/squadron_linux_arm64.tar.gz"
      sha256 "0f04bd4c6d94d6ed5b5b7ecf26341cd7646f67a4c8a0c4c8b5c92aa255de0cc3"
      def install
        bin.install "squadron"
      end
    end
  end

  test do
    system "#{bin}/squadron", "--help"
  end
end
